# Generated by Django 4.2.13 on 2024-05-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_diff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('sel_1', models.CharField(max_length=100)),
                ('sel_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('sel_1', models.CharField(max_length=100)),
                ('sel_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_diff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.BooleanField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOPcardAPI_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Act_TF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.BooleanField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOPcardAPI_app.action')),
            ],
        ),
    ]
